package main

import (
	"embed"
	"github.com/sjqzhang/gdi"
	p1 "go-web-mini/apps/cms/controller"
	p2 "go-web-mini/apps/cms/model"
	p3 "go-web-mini/apps/cms/repository"
	p4 "go-web-mini/apps/cms/service"
	p5 "go-web-mini/apps/cms/vo"
	p6 "go-web-mini/apps/system/controller"
	p7 "go-web-mini/apps/system/dto"
	p8 "go-web-mini/apps/system/model"
	p9 "go-web-mini/apps/system/repository"
	p10 "go-web-mini/apps/system/service"
	p11 "go-web-mini/apps/system/vo"
	p12 "go-web-mini/apps/workflow/bpmn_engine"
	p13 "go-web-mini/apps/workflow/controller"
	p15 "go-web-mini/apps/workflow/listener"
	p16 "go-web-mini/apps/workflow/model"
	p17 "go-web-mini/apps/workflow/repository"
	p18 "go-web-mini/apps/workflow/service"
	p19 "go-web-mini/apps/workflow/spec/BPMN20"
	p22 "go-web-mini/apps/workflow/vo"
	p23 "go-web-mini/config"
	p25 "go-web-mini/generator"
	p26 "go-web-mini/global"
)

//go:embed apps/system/repository apps/system/model config generator middleware util apps/workflow/listener apps/workflow/spec/BPMN20 apps/workflow/spec/BPMN20/activity global apps/cms/repository apps/cms/model apps/workflow/controller apps/workflow/vo apps/cms/controller apps/workflow/model routes apps/workflow/errcode apps/cms/vo apps/system/service apps/workflow/service docs apps/cms/service apps/system/vo apps/workflow/bpmn_engine apps/workflow/spec/BPMN20/process_instance response apps/system/dto apps/workflow/repository apps/system/controller
var gdiEmbedFiles embed.FS

func init() {
	gdi.SetEmbedFs(&gdiEmbedFiles)
	_ = gdi.GDIPool{}
	gdi.PlaceHolder((*p1.ArticleController)(nil))
	gdi.PlaceHolder((*p2.Article)(nil))
	gdi.PlaceHolder((*p2.ArticleQuery)(nil))
	gdi.PlaceHolder((*p2.Model)(nil))
	gdi.PlaceHolder((*p2.PagerModel)(nil))
	gdi.PlaceHolder((*p3.ArticleRepository)(nil))
	gdi.PlaceHolder((*p4.ArticleService)(nil))
	gdi.PlaceHolder((*p5.ArticleResponse)(nil))
	gdi.PlaceHolder((*p5.Article)(nil))
	gdi.PlaceHolder((*p5.ListArticleResponse)(nil))
	gdi.PlaceHolder((*p5.ListArticleRequest)(nil))
	gdi.PlaceHolder((*p5.GetArticleResponse)(nil))
	gdi.PlaceHolder((*p5.CreateArticleRequest)(nil))
	gdi.PlaceHolder((*p5.CreateArticleResponse)(nil))
	gdi.PlaceHolder((*p5.UpdateArticleRequest)(nil))
	gdi.PlaceHolder((*p5.UpdateArticleResponse)(nil))
	gdi.PlaceHolder((*p5.DeleteArticleRequest)(nil))
	gdi.PlaceHolder((*p5.GetArticleRequest)(nil))
	gdi.PlaceHolder((*p5.DeleteArticleResponse)(nil))
	gdi.PlaceHolder((*p5.Response)(nil))
	gdi.PlaceHolder((*p6.ApiController)(nil))
	gdi.PlaceHolder((*p6.MenuController)(nil))
	gdi.PlaceHolder((*p6.OperationLogController)(nil))
	gdi.PlaceHolder((*p6.RoleController)(nil))
	gdi.PlaceHolder((*p6.TableMetadataController)(nil))
	gdi.PlaceHolder((*p6.UserController)(nil))
	gdi.PlaceHolder((*p7.ApiTreeDto)(nil))
	gdi.PlaceHolder((*p7.UserInfoDto)(nil))
	gdi.PlaceHolder((*p7.UsersDto)(nil))
	gdi.PlaceHolder((*p8.Api)(nil))
	gdi.PlaceHolder((*p8.RoleCasbin)(nil))
	gdi.PlaceHolder((*p8.Model)(nil))
	gdi.PlaceHolder((*p8.PagerModel)(nil))
	gdi.PlaceHolder((*p8.Menu)(nil))
	gdi.PlaceHolder((*p8.OperationLog)(nil))
	gdi.PlaceHolder((*p8.Role)(nil))
	gdi.PlaceHolder((*p8.TableMetadata)(nil))
	gdi.PlaceHolder((*p8.TableMetadataQuery)(nil))
	gdi.PlaceHolder((*p8.User)(nil))
	gdi.PlaceHolder((*p9.ApiRepository)(nil))
	gdi.PlaceHolder((*p9.MenuRepository)(nil))
	gdi.PlaceHolder((*p9.OperationLogRepository)(nil))
	gdi.PlaceHolder((*p9.RoleRepository)(nil))
	gdi.PlaceHolder((*p9.TableMetadataRepository)(nil))
	gdi.PlaceHolder((*p9.UserRepository)(nil))
	gdi.PlaceHolder((*p10.TableMetadataService)(nil))
	gdi.PlaceHolder((*p11.ApiListRequest)(nil))
	gdi.PlaceHolder((*p11.CreateApiRequest)(nil))
	gdi.PlaceHolder((*p11.UpdateApiRequest)(nil))
	gdi.PlaceHolder((*p11.DeleteApiRequest)(nil))
	gdi.PlaceHolder((*p11.Response)(nil))
	gdi.PlaceHolder((*p11.CreateMenuRequest)(nil))
	gdi.PlaceHolder((*p11.UpdateMenuRequest)(nil))
	gdi.PlaceHolder((*p11.DeleteMenuRequest)(nil))
	gdi.PlaceHolder((*p11.OperationLogListRequest)(nil))
	gdi.PlaceHolder((*p11.DeleteOperationLogRequest)(nil))
	gdi.PlaceHolder((*p11.CreateRoleRequest)(nil))
	gdi.PlaceHolder((*p11.RoleListRequest)(nil))
	gdi.PlaceHolder((*p11.DeleteRoleRequest)(nil))
	gdi.PlaceHolder((*p11.UpdateRoleMenusRequest)(nil))
	gdi.PlaceHolder((*p11.UpdateRoleApisRequest)(nil))
	gdi.PlaceHolder((*p11.TableMetadataResponse)(nil))
	gdi.PlaceHolder((*p11.TableMetadata)(nil))
	gdi.PlaceHolder((*p11.ListTableMetadataResponse)(nil))
	gdi.PlaceHolder((*p11.ListTableMetadataRequest)(nil))
	gdi.PlaceHolder((*p11.GetTableMetadataResponse)(nil))
	gdi.PlaceHolder((*p11.CreateTableMetadataRequest)(nil))
	gdi.PlaceHolder((*p11.CreateTableMetadataResponse)(nil))
	gdi.PlaceHolder((*p11.UpdateTableMetadataRequest)(nil))
	gdi.PlaceHolder((*p11.UpdateTableMetadataResponse)(nil))
	gdi.PlaceHolder((*p11.DeleteTableMetadataRequest)(nil))
	gdi.PlaceHolder((*p11.GetTableMetadataRequest)(nil))
	gdi.PlaceHolder((*p11.DeleteTableMetadataResponse)(nil))
	gdi.PlaceHolder((*p11.RegisterAndLoginRequest)(nil))
	gdi.PlaceHolder((*p11.CreateUserRequest)(nil))
	gdi.PlaceHolder((*p11.UserListRequest)(nil))
	gdi.PlaceHolder((*p11.DeleteUserRequest)(nil))
	gdi.PlaceHolder((*p11.ChangePwdRequest)(nil))
	gdi.PlaceHolder((*p12.MessageSubscription)(nil))
	gdi.PlaceHolder((*p12.CatchEvent)(nil))
	gdi.PlaceHolder((*p12.ActivatedJob)(nil))
	gdi.PlaceHolder((*p12.ProcessInstanceInfo)(nil))
	gdi.PlaceHolder((*p12.ProcessInfo)(nil))
	gdi.PlaceHolder((*p12.BpmnEngineState)(nil))
	gdi.PlaceHolder((*p12.Timer)(nil))
	gdi.PlaceHolder((*p13.CommandController)(nil))
	gdi.PlaceHolder((*p13.InstanceController)(nil))
	gdi.PlaceHolder((*p13.SchemaController)(nil))
	gdi.PlaceHolder((*p13.TransitionController)(nil))
	gdi.PlaceHolder((*p13.VariablesController)(nil))
	gdi.PlaceHolder((*p15.OrApprovalListener)(nil))
	gdi.PlaceHolder((*p15.ConditionsExpressionChecker)(nil))
	gdi.PlaceHolder((*p16.CaughtEventsTab)(nil))
	gdi.PlaceHolder((*p16.InstanceTab)(nil))
	gdi.PlaceHolder((*p16.LockerTab)(nil))
	gdi.PlaceHolder((*p16.LogTab)(nil))
	gdi.PlaceHolder((*p16.SchemeTab)(nil))
	gdi.PlaceHolder((*p16.TransitionsTab)(nil))
	gdi.PlaceHolder((*p17.CaughtEventsDBRepo)(nil))
	gdi.PlaceHolder((*p17.InstanceDBRepo)(nil))
	gdi.PlaceHolder((*p17.LockerDBRepo)(nil))
	gdi.PlaceHolder((*p17.SchemeDBRepo)(nil))
	gdi.PlaceHolder((*p17.TransitionsDBRepo)(nil))
	gdi.PlaceHolder((*p18.InstanceService)(nil))
	gdi.PlaceHolder((*p18.CommandEngine)(nil))
	gdi.PlaceHolder((*p18.LockerService)(nil))
	gdi.PlaceHolder((*p18.SchemeService)(nil))
	gdi.PlaceHolder((*p18.VariablesService)(nil))
	gdi.PlaceHolder((*p19.TDefinitions)(nil))
	gdi.PlaceHolder((*p19.TProcess)(nil))
	gdi.PlaceHolder((*p19.TSequenceFlow)(nil))
	gdi.PlaceHolder((*p19.TExpression)(nil))
	gdi.PlaceHolder((*p19.TStartEvent)(nil))
	gdi.PlaceHolder((*p19.TEndEvent)(nil))
	gdi.PlaceHolder((*p19.TServiceTask)(nil))
	gdi.PlaceHolder((*p19.TParallelGateway)(nil))
	gdi.PlaceHolder((*p19.TExclusiveGateway)(nil))
	gdi.PlaceHolder((*p19.TIntermediateCatchEvent)(nil))
	gdi.PlaceHolder((*p19.TEventBasedGateway)(nil))
	gdi.PlaceHolder((*p19.TMessageEventDefinition)(nil))
	gdi.PlaceHolder((*p19.TTimerEventDefinition)(nil))
	gdi.PlaceHolder((*p19.TMessage)(nil))
	gdi.PlaceHolder((*p19.TTimeDuration)(nil))
	gdi.PlaceHolder((*p19.TExtensionElements)(nil))
	gdi.PlaceHolder((*p19.TExtensionProperties)(nil))
	gdi.PlaceHolder((*p19.TExtensionProperty)(nil))
	gdi.PlaceHolder((*p19.TExtensionExecutionListener)(nil))
	gdi.PlaceHolder((*p19.TExtensionExecutionListenerField)(nil))
	gdi.PlaceHolder((*p22.GetInstanceAvailableCommands)(nil))
	gdi.PlaceHolder((*p22.Command)(nil))
	gdi.PlaceHolder((*p22.CommandExecResp)(nil))
	gdi.PlaceHolder((*p22.InsIdTransitionIds)(nil))
	gdi.PlaceHolder((*p22.CommandExecBatchResp)(nil))
	gdi.PlaceHolder((*p22.InsAvailableCommands)(nil))
	gdi.PlaceHolder((*p22.GetInsListAvailableCommandsResp)(nil))
	gdi.PlaceHolder((*p22.CommResp)(nil))
	gdi.PlaceHolder((*p22.InstanceTransitions)(nil))
	gdi.PlaceHolder((*p22.InstanceTransition)(nil))
	gdi.PlaceHolder((*p22.CreateInstanceResp)(nil))
	gdi.PlaceHolder((*p22.ServiceTasks)(nil))
	gdi.PlaceHolder((*p22.Variables)(nil))
	gdi.PlaceHolder((*p22.GetInstanceResp)(nil))
	gdi.PlaceHolder((*p22.InstanceTasks)(nil))
	gdi.PlaceHolder((*p22.GetInstanceTasksResp)(nil))
	gdi.PlaceHolder((*p22.InstanceSchemaCode)(nil))
	gdi.PlaceHolder((*p22.GetInstanceSchemaCodeResp)(nil))
	gdi.PlaceHolder((*p22.InstanceCommand)(nil))
	gdi.PlaceHolder((*p22.GetInstanceCommandResp)(nil))
	gdi.PlaceHolder((*p22.CreateInstance)(nil))
	gdi.PlaceHolder((*p22.SetInstanceVariablesReq)(nil))
	gdi.PlaceHolder((*p22.GetInstanceReq)(nil))
	gdi.PlaceHolder((*p22.GetInstanceVariablesReq)(nil))
	gdi.PlaceHolder((*p22.GetInstanceTasksReq)(nil))
	gdi.PlaceHolder((*p22.InstanceSchemaCodeReq)(nil))
	gdi.PlaceHolder((*p22.GetInstanceCommandReq)(nil))
	gdi.PlaceHolder((*p22.GetInstanceAvailableCommandsReq)(nil))
	gdi.PlaceHolder((*p22.GetInsListAvailableCommandsReq)(nil))
	gdi.PlaceHolder((*p22.CommandExecution)(nil))
	gdi.PlaceHolder((*p22.CommandExecutionBatch)(nil))
	gdi.PlaceHolder((*p22.CommandExecutionBatchReq)(nil))
	gdi.PlaceHolder((*p22.CommandOptimize)(nil))
	gdi.PlaceHolder((*p22.CommandExecutionOptimizeReq)(nil))
	gdi.PlaceHolder((*p22.GetInstanceTransitions)(nil))
	gdi.PlaceHolder((*p22.GetInstanceTransitionsByIds)(nil))
	gdi.PlaceHolder((*p22.GetSchemaInfosResp)(nil))
	gdi.PlaceHolder((*p22.SchemaInfo)(nil))
	gdi.PlaceHolder((*p22.SchemaFileResp)(nil))
	gdi.PlaceHolder((*p22.GetSchemaReq)(nil))
	gdi.PlaceHolder((*p22.SchemaFileReq)(nil))
	gdi.PlaceHolder((*p22.GetVariablesResp)(nil))
	gdi.PlaceHolder((*p23.SystemConfig)(nil))
	gdi.PlaceHolder((*p23.LogsConfig)(nil))
	gdi.PlaceHolder((*p23.MysqlConfig)(nil))
	gdi.PlaceHolder((*p23.CasbinConfig)(nil))
	gdi.PlaceHolder((*p23.JwtConfig)(nil))
	gdi.PlaceHolder((*p23.RateLimitConfig)(nil))
	gdi.PlaceHolder((*p23.RedisConfig)(nil))
	gdi.PlaceHolder((*p25.FieldResult)(nil))
	gdi.PlaceHolder((*p25.TableResult)(nil))
	gdi.PlaceHolder((*p25.CommonObject)(nil))
	gdi.PlaceHolder((*p25.Config)(nil))
	gdi.PlaceHolder((*p25.IndexResult)(nil))
	gdi.PlaceHolder((*p26.CustomLogger)(nil))
}
