basePath: /api
definitions:
  vo.Branch:
    properties:
      branch_name:
        description: branch_name
        type: string
      branch_type:
        description: branch_type
        type: integer
      commit_id:
        description: commit_id
        type: string
      commit_time:
        description: commit_time
        type: integer
      commit_title:
        description: commit_title
        type: string
      committer:
        description: committer
        type: string
      created_at:
        description: created_at
        type: string
      creator:
        description: creator
        type: string
      deleted_at:
        description: deleted_at
        type: string
      id:
        description: id
        type: integer
      is_dev:
        description: is_dev
        type: integer
      jira_key:
        description: jira_key
        type: string
      repo:
        description: repo
        type: string
      sync_time:
        description: sync_time
        type: integer
      updated_at:
        description: updated_at
        type: string
    type: object
  vo.CreateBranchResponse:
    properties:
      code:
        description: 0:成功，非0:失败
        type: integer
      data:
        $ref: '#/definitions/vo.Branch'
      message:
        description: 提示信息
        type: string
    type: object
  vo.CreateNewsResponse:
    properties:
      code:
        description: 0:成功，非0:失败
        type: integer
      data:
        $ref: '#/definitions/vo.News'
      message:
        description: 提示信息
        type: string
    type: object
  vo.DeleteBranchResponse:
    properties:
      code:
        description: 0:成功，非0:失败
        type: integer
      data:
        type: integer
      message:
        description: 提示信息
        type: string
    type: object
  vo.DeleteNewsResponse:
    properties:
      code:
        description: 0:成功，非0:失败
        type: integer
      data:
        type: integer
      message:
        description: 提示信息
        type: string
    type: object
  vo.GetBranchResponse:
    properties:
      code:
        description: 0:成功，非0:失败
        type: integer
      data:
        $ref: '#/definitions/vo.Branch'
      message:
        description: 提示信息
        type: string
    type: object
  vo.GetNewsResponse:
    properties:
      code:
        description: 0:成功，非0:失败
        type: integer
      data:
        $ref: '#/definitions/vo.News'
      message:
        description: 提示信息
        type: string
    type: object
  vo.ListBranchResponse:
    properties:
      code:
        description: 0:成功，非0:失败
        type: integer
      data:
        $ref: '#/definitions/vo.PagerBranch'
      message:
        description: 提示信息
        type: string
    type: object
  vo.ListNewsResponse:
    properties:
      code:
        description: 0:成功，非0:失败
        type: integer
      data:
        $ref: '#/definitions/vo.PagerNews'
      message:
        description: 提示信息
        type: string
    type: object
  vo.News:
    properties:
      content:
        description: 新闻内容
        type: string
      created_at:
        description: created_at
        type: string
      creator:
        description: 新闻创建者
        type: string
      deleted_at:
        description: deleted_at
        type: string
      id:
        description: id
        type: integer
      title:
        description: 新闻标题
        type: string
      updated_at:
        description: updated_at
        type: string
    type: object
  vo.PagerBranch:
    properties:
      extra:
        additionalProperties: true
        type: object
      list:
        items:
          $ref: '#/definitions/vo.Branch'
        type: array
      pageNum:
        type: integer
      pageSize:
        type: integer
      total:
        type: integer
    type: object
  vo.PagerNews:
    properties:
      extra:
        additionalProperties: true
        type: object
      list:
        items:
          $ref: '#/definitions/vo.News'
        type: array
      pageNum:
        type: integer
      pageSize:
        type: integer
      total:
        type: integer
    type: object
  vo.UpdateBranchResponse:
    properties:
      code:
        description: 0:成功，非0:失败
        type: integer
      data:
        $ref: '#/definitions/vo.Branch'
      message:
        description: 提示信息
        type: string
    type: object
  vo.UpdateNewsResponse:
    properties:
      code:
        description: 0:成功，非0:失败
        type: integer
      data:
        $ref: '#/definitions/vo.News'
      message:
        description: 提示信息
        type: string
    type: object
info:
  contact: {}
  description: This is a sample server Petstore server.
  termsOfService: http://localhost
  title: Swagger Example API
  version: v1
paths:
  /access/list/user/:userId:
    get:
      responses: {}
      tags:
      - menu
  /api/create:
    post:
      responses: {}
      tags:
      - api
  /api/delete/batch:
    delete:
      responses: {}
      tags:
      - api
  /api/list:
    get:
      responses: {}
      tags:
      - api
  /api/tree:
    get:
      responses: {}
      tags:
      - api
  /api/update/:apiId:
    patch:
      responses: {}
      tags:
      - api
  /branch:
    delete:
      consumes:
      - application/json
      description: 批量删除branch
      parameters:
      - collectionFormat: csv
        description: 待编号
        in: query
        items:
          type: integer
        name: ids
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/vo.DeleteBranchResponse'
      security:
      - JWT: []
      tags:
      - Branch
    get:
      consumes:
      - application/json
      description: 查询单个branch
      parameters:
      - description: branch_name
        in: query
        name: branch_name
        type: string
      - description: branch_type
        in: query
        name: branch_type
        type: integer
      - description: commit_id
        in: query
        name: commit_id
        type: string
      - description: commit_time
        in: query
        name: commit_time
        type: integer
      - description: commit_title
        in: query
        name: commit_title
        type: string
      - description: committer
        in: query
        name: committer
        type: string
      - description: creator
        in: query
        name: creator
        type: string
      - description: is_dev
        in: query
        name: is_dev
        type: integer
      - description: jira_key
        in: query
        name: jira_key
        type: string
      - description: 第几页
        in: query
        name: pageNum
        type: integer
      - description: 每页多少条
        in: query
        name: pageSize
        type: integer
      - description: repo
        in: query
        name: repo
        type: string
      - description: sync_time
        in: query
        name: sync_time
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/vo.ListBranchResponse'
      security:
      - JWT: []
      tags:
      - Branch
    post:
      consumes:
      - application/json
      description: 创建branch
      parameters:
      - description: branch_name
        in: query
        name: branch_name
        type: string
      - description: branch_type
        in: query
        name: branch_type
        type: integer
      - description: commit_id
        in: query
        name: commit_id
        type: string
      - description: commit_time
        in: query
        name: commit_time
        type: integer
      - description: commit_title
        in: query
        name: commit_title
        type: string
      - description: committer
        in: query
        name: committer
        type: string
      - description: creator
        in: query
        name: creator
        type: string
      - description: is_dev
        in: query
        name: is_dev
        type: integer
      - description: jira_key
        in: query
        name: jira_key
        type: string
      - description: repo
        in: query
        name: repo
        type: string
      - description: sync_time
        in: query
        name: sync_time
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/vo.CreateBranchResponse'
      security:
      - JWT: []
      tags:
      - Branch
  /branch/:id:
    get:
      consumes:
      - application/json
      description: 查询branch列表
      parameters:
      - description: 待编号
        in: query
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/vo.GetBranchResponse'
      security:
      - JWT: []
      tags:
      - Branch
    put:
      consumes:
      - application/json
      description: 更新branch
      parameters:
      - description: branch_name
        in: query
        name: branch_name
        type: string
      - description: branch_type
        in: query
        name: branch_type
        type: integer
      - description: commit_id
        in: query
        name: commit_id
        type: string
      - description: commit_time
        in: query
        name: commit_time
        type: integer
      - description: commit_title
        in: query
        name: commit_title
        type: string
      - description: committer
        in: query
        name: committer
        type: string
      - description: creator
        in: query
        name: creator
        type: string
      - in: query
        name: id
        type: integer
      - description: is_dev
        in: query
        name: is_dev
        type: integer
      - description: jira_key
        in: query
        name: jira_key
        type: string
      - description: repo
        in: query
        name: repo
        type: string
      - description: sync_time
        in: query
        name: sync_time
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/vo.UpdateBranchResponse'
      security:
      - JWT: []
      tags:
      - Branch
  /log/operation/delete/batch:
    delete:
      responses: {}
      tags:
      - log
  /log/operation/list:
    get:
      responses: {}
      tags:
      - log
  /menu/access/tree/:userId:
    get:
      responses: {}
      tags:
      - menu
  /menu/create:
    post:
      responses: {}
      tags:
      - menu
  /menu/delete/batch:
    delete:
      responses: {}
      tags:
      - menu
  /menu/list:
    get:
      responses: {}
      tags:
      - menu
  /menu/tree:
    get:
      responses: {}
      tags:
      - menu
  /menu/update/:menuId:
    patch:
      responses: {}
      tags:
      - menu
  /news:
    delete:
      consumes:
      - application/json
      description: 批量删除新闻
      parameters:
      - collectionFormat: csv
        description: 待编号
        in: query
        items:
          type: integer
        name: ids
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/vo.DeleteNewsResponse'
      security:
      - JWT: []
      tags:
      - News
    get:
      consumes:
      - application/json
      description: 查询单个新闻
      parameters:
      - description: 新闻内容
        in: query
        name: content
        type: string
      - description: 新闻创建者
        in: query
        name: creator
        type: string
      - description: 第几页
        in: query
        name: pageNum
        type: integer
      - description: 每页多少条
        in: query
        name: pageSize
        type: integer
      - description: 新闻标题
        in: query
        name: title
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/vo.ListNewsResponse'
      security:
      - JWT: []
      tags:
      - News
    post:
      consumes:
      - application/json
      description: 创建新闻
      parameters:
      - description: 新闻内容
        in: query
        name: content
        type: string
      - description: 新闻创建者
        in: query
        name: creator
        type: string
      - description: 新闻标题
        in: query
        name: title
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/vo.CreateNewsResponse'
      security:
      - JWT: []
      tags:
      - News
  /news/:id:
    get:
      consumes:
      - application/json
      description: 查询新闻列表
      parameters:
      - description: 待编号
        in: query
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/vo.GetNewsResponse'
      security:
      - JWT: []
      tags:
      - News
    put:
      consumes:
      - application/json
      description: 更新新闻
      parameters:
      - description: 新闻内容
        in: query
        name: content
        type: string
      - description: 新闻创建者
        in: query
        name: creator
        type: string
      - in: query
        name: id
        type: integer
      - description: 新闻标题
        in: query
        name: title
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/vo.UpdateNewsResponse'
      security:
      - JWT: []
      tags:
      - News
  /role/apis/get/:roleId:
    get:
      responses: {}
      tags:
      - role
  /role/apis/update/:roleId:
    patch:
      responses: {}
      tags:
      - role
  /role/create:
    post:
      responses: {}
      tags:
      - role
  /role/delete/batch:
    delete:
      responses: {}
      tags:
      - role
  /role/list:
    get:
      responses: {}
      tags:
      - role
  /role/menus/get/:roleId:
    get:
      responses: {}
      tags:
      - role
  /role/menus/update/:roleId:
    patch:
      responses: {}
      tags:
      - role
  /role/update/:roleId:
    patch:
      responses: {}
      tags:
      - role
  /user:
    post:
      responses: {}
      tags:
      - user
  /user/changePwd:
    put:
      responses: {}
      tags:
      - user
  /user/delete/batch:
    delete:
      responses: {}
      tags:
      - user
  /user/info:
    post:
      responses: {}
      tags:
      - user
  /user/list:
    get:
      responses: {}
      tags:
      - user
  /user/update/:userId:
    patch:
      responses: {}
      tags:
      - user
schemes:
- http
- https
securityDefinitions:
  JWT:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
