basePath: /api
definitions:
  vo.Branch:
    properties:
      branch_name:
        description: branch_name
        type: string
      branch_type:
        description: branch_type
        type: integer
      commit_id:
        description: commit_id
        type: string
      commit_time:
        description: commit_time
        type: integer
      commit_title:
        description: commit_title
        type: string
      committer:
        description: committer
        type: string
      created_at:
        description: created_at
        type: string
      creator:
        description: creator
        type: string
      deleted_at:
        description: deleted_at
        type: string
      id:
        description: id
        type: integer
      is_dev:
        description: is_dev
        type: integer
      jira_key:
        description: jira_key
        type: string
      repo:
        description: repo
        type: string
      sync_time:
        description: sync_time
        type: integer
      updated_at:
        description: updated_at
        type: string
    type: object
  vo.CreateBranchResponse:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/vo.Branch'
      message:
        type: string
    type: object
  vo.DeleteBranchResponse:
    properties:
      code:
        type: integer
      data:
        type: integer
      message:
        type: string
    type: object
  vo.GetBranchResponse:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/vo.Branch'
      message:
        type: string
    type: object
  vo.ListBranchResponse:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/vo.PagerBranch'
      message:
        type: string
    type: object
  vo.PagerBranch:
    properties:
      extra:
        additionalProperties: true
        type: object
      list:
        items:
          $ref: '#/definitions/vo.Branch'
        type: array
      pageNum:
        type: integer
      pageSize:
        type: integer
      total:
        type: integer
    type: object
  vo.UpdateBranchResponse:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/vo.Branch'
      message:
        type: string
    type: object
info:
  contact: {}
  description: This is a sample server Petstore server.
  termsOfService: http://localhost
  title: Swagger Example API
  version: v1
paths:
  /access/list/user/:userId:
    get:
      responses: {}
      tags:
      - menu
  /api/create:
    post:
      responses: {}
      tags:
      - api
  /api/delete/batch:
    delete:
      responses: {}
      tags:
      - api
  /api/list:
    get:
      responses: {}
      tags:
      - api
  /api/tree:
    get:
      responses: {}
      tags:
      - api
  /api/update/:apiId:
    patch:
      responses: {}
      tags:
      - api
  /branch:
    delete:
      consumes:
      - application/json
      description: 批量删除branch
      parameters:
      - collectionFormat: csv
        in: query
        items:
          type: integer
        name: ids
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/vo.DeleteBranchResponse'
      security:
      - JWT: []
      tags:
      - branch
    get:
      consumes:
      - application/json
      description: 查询单个branch
      parameters:
      - description: branch_name
        in: query
        name: branch_name
        type: string
      - description: branch_type
        in: query
        name: branch_type
        type: integer
      - description: commit_id
        in: query
        name: commit_id
        type: string
      - description: commit_time
        in: query
        name: commit_time
        type: integer
      - description: commit_title
        in: query
        name: commit_title
        type: string
      - description: committer
        in: query
        name: committer
        type: string
      - description: creator
        in: query
        name: creator
        type: string
      - description: is_dev
        in: query
        name: is_dev
        type: integer
      - description: jira_key
        in: query
        name: jira_key
        type: string
      - in: query
        name: pageNum
        type: integer
      - in: query
        name: pageSize
        type: integer
      - description: repo
        in: query
        name: repo
        type: string
      - description: sync_time
        in: query
        name: sync_time
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/vo.ListBranchResponse'
      security:
      - JWT: []
      tags:
      - branch
    post:
      consumes:
      - application/json
      description: 创建branch
      parameters:
      - description: branch_name
        in: query
        name: branch_name
        type: string
      - description: branch_type
        in: query
        name: branch_type
        type: integer
      - description: commit_id
        in: query
        name: commit_id
        type: string
      - description: commit_time
        in: query
        name: commit_time
        type: integer
      - description: commit_title
        in: query
        name: commit_title
        type: string
      - description: committer
        in: query
        name: committer
        type: string
      - description: creator
        in: query
        name: creator
        type: string
      - description: is_dev
        in: query
        name: is_dev
        type: integer
      - description: jira_key
        in: query
        name: jira_key
        type: string
      - description: repo
        in: query
        name: repo
        type: string
      - description: sync_time
        in: query
        name: sync_time
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/vo.CreateBranchResponse'
      security:
      - JWT: []
      tags:
      - branch
  /branch/:id:
    get:
      consumes:
      - application/json
      description: 查询branch列表
      parameters:
      - in: query
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/vo.GetBranchResponse'
      security:
      - JWT: []
      tags:
      - branch
    put:
      consumes:
      - application/json
      description: 更新branch
      parameters:
      - description: branch_name
        in: query
        name: branch_name
        type: string
      - description: branch_type
        in: query
        name: branch_type
        type: integer
      - description: commit_id
        in: query
        name: commit_id
        type: string
      - description: commit_time
        in: query
        name: commit_time
        type: integer
      - description: commit_title
        in: query
        name: commit_title
        type: string
      - description: committer
        in: query
        name: committer
        type: string
      - description: creator
        in: query
        name: creator
        type: string
      - in: query
        name: id
        type: integer
      - description: is_dev
        in: query
        name: is_dev
        type: integer
      - description: jira_key
        in: query
        name: jira_key
        type: string
      - description: repo
        in: query
        name: repo
        type: string
      - description: sync_time
        in: query
        name: sync_time
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/vo.UpdateBranchResponse'
      security:
      - JWT: []
      tags:
      - branch
  /branchTab:
    delete:
      description: 批量删除branch
      responses: {}
    get:
      description: 查询单个branch
      responses: {}
    post:
      description: 创建branch
      responses: {}
  /branchTab/:id:
    delete:
      description: 删除单个branch
      responses: {}
    get:
      description: 查询branch列表
      responses: {}
    put:
      description: 更新branch
      responses: {}
  /log/operation/delete/batch:
    delete:
      responses: {}
      tags:
      - log
  /log/operation/list:
    get:
      responses: {}
      tags:
      - log
  /menu/access/tree/:userId:
    get:
      responses: {}
      tags:
      - menu
  /menu/create:
    post:
      responses: {}
      tags:
      - menu
  /menu/delete/batch:
    delete:
      responses: {}
      tags:
      - menu
  /menu/list:
    get:
      responses: {}
      tags:
      - menu
  /menu/tree:
    get:
      responses: {}
      tags:
      - menu
  /menu/update/:menuId:
    patch:
      responses: {}
      tags:
      - menu
  /news:
    delete:
      description: 批量删除news
      responses: {}
    get:
      description: 查询单个news
      responses: {}
    post:
      description: 创建news
      responses: {}
  /news/:id:
    delete:
      description: 删除单个news
      responses: {}
    get:
      description: 查询news列表
      responses: {}
    put:
      description: 更新news
      responses: {}
  /role/apis/get/:roleId:
    get:
      responses: {}
      tags:
      - role
  /role/apis/update/:roleId:
    patch:
      responses: {}
      tags:
      - role
  /role/create:
    post:
      responses: {}
      tags:
      - role
  /role/delete/batch:
    delete:
      responses: {}
      tags:
      - role
  /role/list:
    get:
      responses: {}
      tags:
      - role
  /role/menus/get/:roleId:
    get:
      responses: {}
      tags:
      - role
  /role/menus/update/:roleId:
    patch:
      responses: {}
      tags:
      - role
  /role/update/:roleId:
    patch:
      responses: {}
      tags:
      - role
  /user:
    post:
      responses: {}
      tags:
      - user
  /user/changePwd:
    put:
      responses: {}
      tags:
      - user
  /user/delete/batch:
    delete:
      responses: {}
      tags:
      - user
  /user/info:
    post:
      responses: {}
      tags:
      - user
  /user/list:
    get:
      responses: {}
      tags:
      - user
  /user/update/:userId:
    patch:
      responses: {}
      tags:
      - user
schemes:
- http
- https
securityDefinitions:
  JWT:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
